# onboards data generated by DOHMH into the database
from models import Borough, ViolationCode, Restaurant, Inspection, Collection, new_session
from sqlalchemy.sql import select
import json

def make_serializer(model, keys={'id'}, exclude_keys=True):
    keys = list(filter(lambda k: k not in keys if exclude_keys else k in keys,
                            [key.key for key in model.__table__.columns]))
    return lambda *instances: [{k: getattr(inst, k) for k in keys} for inst in instances]

def make_prepared_stmt(model, keys):
    return 'insert into %s (%s) values (%s)' % (model.__tablename__, ', '.join(keys), '?' * len(keys))
  
def bulk_save(s, data, size):
    limit = size
    offset = 0
    SZ = len(data)
    while True:
        s.bulk_save_objects(data[offset:offset+limit])
        s.commit()
        if offset+limit > SZ:
            break
        offset += limit

def data_onboard(data):
    s = new_session()
    getOrElse = lambda o, k, d: o[k] if k in o else d
    violation_code = Collection(ViolationCode, lambda vc: vc.code)
    borough = Collection(Borough, lambda b: b.borough)
    restaurant = Collection(Restaurant, lambda r: r.camis)
    inspection = []
    for row in data:
        if 'boro' in row:
            borough.insert(Borough(borough=row['boro']))
        if 'violation_code' in row:
            violation_code.insert(ViolationCode(code=row['violation_code']))
        if 'camis' in row:
            restaurant.insert(Restaurant(
                            camis=getOrElse(row, 'camis', None),
                            dba=getOrElse(row, 'dba', None),
                            street=getOrElse(row, 'street', None),
                            phone=getOrElse(row, 'phone', None),
                            cuisine_description=getOrElse(row, 'cuisine_description', None),
                            borough=getOrElse(row, 'boro', None),
                            building=getOrElse(row, 'building', None),
                            zipcode=getOrElse(row, 'zipcode', None)))
        inspection.append(Inspection(
                                    restaurant=getOrElse(row, 'camis', None),
                                    record_date=getOrElse(row, 'record_date', None),
                                    violation_code=getOrElse(row, 'violation_code', None),
                                    violation_description=getOrElse(row, 'violation_description', None),
                                    score=int(row['score']) if 'score' in row else None,
                                    inspection_date=getOrElse(row, 'inspection_date', None),
                                    inspection_type=getOrElse(row, 'inspection_type', None),
                                    critical_flag=getOrElse(row, 'critical_flag', None)))

    s.bulk_save_objects(borough.getall())
    s.bulk_save_objects(violation_code.getall())
    s.commit()
    boroughs = set([r.borough for r in restaurant.getall()])
    boroughs = {b[1]: b[0] for b in s.query(Borough.__table__.c.id, Borough.__table__.c.borough)}
    for r in restaurant.getall():
        if r.borough != None:
            r.borough = boroughs[r.borough]
    bulk_save(s, restaurant.getall(), 1500)
    codes = set([i.violation_code for i in inspection])
    codes = {c[1]: c[0] for c in s.query(ViolationCode.__table__.c.id, ViolationCode.__table__.c.code)}
    camis = set([r.camis for r in restaurant.getall()])
    camis = {c[1]: c[0] for c in s.query(Restaurant.__table__.c.id, Restaurant.__table__.c.camis)}
    for i in inspection:
        if i.restaurant != None:
            i.restaurant = camis[i.restaurant]
        if i.violation_code != None:
            i.violation_code = codes[i.violation_code]
    bulk_save(s, inspection, 1500)
    s.close()

data = []
for i in range(8):
    print("Reading data/%s.json" % i)
    with open('data/%s.json' % i) as f:
        data += json.load(f)

print("Onboarding...")
data_onboard(data)
print("Onboarding completed")
